---
- name: VPN
  hosts: localhost
  vars:
    ansible_python_interpreter: /bin/python3
  vars_files:
  gather_facts: true
  become: true
  pre_tasks:
    - name: docker and boto python packages
      pip:
        name:
          - boto
          - boto3
          - botocore
          - awscli
        executable: /usr/bin/pip3
        state: latest
    - ec2_metadata_facts:
    - name: Retrieve all tags on an instance
      amazon.aws.ec2_tag_info:
        region: "{{ ansible_ec2_placement_region }}"
        resource: "{{ ansible_ec2_instance_id }}"
      register: instance_tags
    - name: Set variables from tags
      set_fact:
        vpn_client: "{{ ('vpn_client' in instance_tags.tags)  and ((instance_tags.tags.vpn_client | lower) == 'true') }}"
    - name: Print tags
      debug:
        msg: 
          - "tags: {{ instance_tags.tags }}"
          - "vpn_client: {{ vpn_client }}"
  roles:
    - dependencies
    - { role: vpn_server, when: "not vpn_client"}

