---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vpn-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.region }}

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vpn-client-openvpn-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vpn-store
    kind: SecretStore
  target:
    name: vpn-client-openvpn-secret
    creationPolicy: Owner
  data:
    - secretKey: ca_cert
      remoteRef:
        key: {{ .Values.vpnClientSecret }}
        property: ca_cert
    - secretKey: public_cert
      remoteRef:
        key: {{ .Values.vpnClientSecret }}
        property: public_cert
    - secretKey: private_cert
      remoteRef:
        key: {{ .Values.vpnClientSecret }}
        property: private_cert
