---
- name: squid configuration
  copy:
    src: squid.conf
    dest: /etc/squid/squid.conf
    owner: root
    group: root
    mode: "0644"
- name: Enable service squid
  systemd:
    name: squid
    enabled: yes
    state: restarted