---
- name: Raspberry PI Openvpn client
  hosts: vpn_client
  vars:
    ansible_python_interpreter: python3
    vpn_server_host: 
  vars_files:
  gather_facts: true
  become: true
  pre_tasks:
    - name: Allow release-info to change for APT repositories
      command: apt-get update -y --allow-releaseinfo-change
    - name: Install openvpn
      apt:
        name: openvpn
    - name: Install iptables-persistent
      apt:
        name: iptables-persistent 
  roles:
    - openvpn
